name: Build docummentation and updated README badges on new release

on:
  release:
    types: [published]

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build documentation
        run: |
          python -m pip install --upgrade pip
          pip install -r ./docs/requirements.txt
          python ./docs/build.py ${{ github.event.release.name }}

      - name: Update README.md badges
        run: |
          python ./docs/generate_readme_badges.py

      - name: Commit updated documentation and badges
        uses: "stefanzweifel    /git-auto-commit-action@v5"
        with:
          commit_message: Documentation for version ${{ github.event.release.name }}
